spring:

  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://localhost:5433/ticketdb
    username: admin
    password: admin

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8081